In [10]:
##reading data from various data source using pandas
import pandas as pd;
from io import StringIO
Data='{"employee_name":"James","email":"james@gmail.com","job_profile":[{"title1":"Team Lead"}]}'
df=pd.read_json(StringIO(Data))
df

  employee_name            email              job_profile
0         James  james@gmail.com  {'title1': 'Team Lead'}

In [9]:
df.to_json()

'{"employee_name":{"0":"James"},"email":{"0":"james@gmail.com"},"job_profile":{"0":{"title1":"Team Lead"}}}'

In [11]:
df.to_json(orient='index')

'{"0":{"employee_name":"James","email":"james@gmail.com","job_profile":{"title1":"Team Lead"}}}'

In [12]:
df.to_json(orient='records')

'[{"employee_name":"James","email":"james@gmail.com","job_profile":{"title1":"Team Lead"}}]'

In [13]:
df=pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv")
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [14]:
df.to_csv("wine.csv")

In [19]:
!pip install lxml

Collecting lxml
  Downloading lxml-6.0.2-cp310-cp310-win_amd64.whl.metadata (3.7 kB)
Downloading lxml-6.0.2-cp310-cp310-win_amd64.whl (4.0 MB)
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   ---------------------------------------  3.9/4.0 MB 13.8 MB/s eta 0:00:01
   ---------------------------------------- 4.0/4.0 MB 12.7 MB/s  0:00:00
Installing collected packages: lxml
Successfully installed lxml-6.0.2

In [23]:
url="https://www.worldometers.info/world-population/population-by-country/"
df=pd.read_html(url)[0]
df

,#,Country (or dependency),Population 2025,Yearly Change,Net Change,Density (P/Km²),Land Area (Km²),Migrants (net),Fert. Rate,Median Age,Urban Pop %,World Share
0,1,India,1463865525,0.89%,12929734,492,2973190,"−495,753",1.94,28.8,37.1%,17.78%
1,2,China,1416096094,−0.23%,"−3,225,184",151,9388211,"−268,126",1.02,40.1,67.5%,17.20%
2,3,United States,347275807,0.54%,1849236,38,9147420,1230663,1.62,38.5,82.8%,4.22%
3,4,Indonesia,285721236,0.79%,2233305,158,1811570,"−39,509",2.10,30.4,59.6%,3.47%
4,5,Pakistan,255219554,1.57%,3950390,331,770880,"−1,235,336",3.50,20.6,34.4%,3.10%
...,...,...,...,...,...,...,...,...,...,...,...,...
228,229,Montserrat,4359,−0.68%,−30,44,100,−9,1.45,41.6,11.5%,0.000053%
229,230,Falkland Islands,3469,−0.03%,−1,0,12170,−17,1.70,42.8,68%,0.000042%
230,231,Tokelau,2608,4.07%,102,261,10,53,2.57,27.3,NaN,0.000032%
231,232,Niue,1821,0.11%,2,7,260,3,2.46,35.7,44.5%,0.000022%
232,233,Holy See,501,1.01%,5,1253,0,13,1.00,57.4,NaN,0.0000061%

In [24]:
df.describe()

,#,Population 2025,Density (P/Km²),Land Area (Km²),Fert. Rate,Median Age
count,233.000000,2.330000e+02,233.000000,2.330000e+02,233.000000,233.000000
mean,117.000000,3.532080e+07,487.673820,5.583427e+05,2.306094,31.896996
std,67.405489,1.391905e+08,2412.937646,1.694270e+06,1.134316,9.860936
min,1.000000,5.010000e+02,0.000000,0.000000e+00,0.690000,14.500000
25%,59.000000,4.663300e+05,38.000000,2.830000e+03,1.470000,22.900000
50%,117.000000,5.731206e+06,98.000000,8.220000e+04,1.940000,32.800000
75%,175.000000,2.407458e+07,256.000000,4.103400e+05,2.950000,39.800000
max,233.000000,1.463866e+09,25732.000000,1.637687e+07,5.940000,57.400000

In [29]:
%pip install beautifulsoup4

Collecting beautifulsoup4
  Downloading beautifulsoup4-4.14.3-py3-none-any.whl.metadata (3.8 kB)
Collecting soupsieve>=1.6.1 (from beautifulsoup4)
  Downloading soupsieve-2.8.1-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\mlstart\day2\venv\lib\site-packages (from beautifulsoup4) (4.15.0)
Downloading beautifulsoup4-4.14.3-py3-none-any.whl (107 kB)
Downloading soupsieve-2.8.1-py3-none-any.whl (36 kB)
Installing collected packages: soupsieve, beautifulsoup4

   ---------------------------------------- 0/2 [soupsieve]
   ---------------------------------------- 0/2 [soupsieve]
   -------------------- ------------------- 1/2 [beautifulsoup4]
   -------------------- ------------------- 1/2 [beautifulsoup4]
   -------------------- ------------------- 1/2 [beautifulsoup4]
   ---------------------------------------- 2/2 [beautifulsoup4]

Successfully installed beautifulsoup4-4.14.3 soupsieve-2.8.1
Note: you may need to restart the kernel to use updated packages.

In [30]:
import bs4
print(bs4.__version__)

4.14.3